window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\victor brambilla\\AppData\\Roaming",
  "AutInstLog": "C:\\ProgramData\\Siemens\\Automation\\Logfiles\\Setup\\",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_2200_UHCKGJDMZVOQMCDI",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-PMAO6FS",
  "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
  "dp0": "C:\\Users\\victor brambilla\\Desktop\\vscode\\desafio crm7\\contacts\\node_modules\\.bin\\",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\victor brambilla\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\victor brambilla",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\victor brambilla",
  "INIT_CWD": "C:\\Users\\victor brambilla\\Desktop\\vscode\\desafio crm7\\contacts",
  "LANG": "pt_BR.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\victor brambilla\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-PMAO6FS",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_config_access": "",
  "npm_config_allow_same_version": "",
  "npm_config_also": "",
  "npm_config_always_auth": "",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"build\"],\"original\":[\"run\",\"build\"]}",
  "npm_config_audit": "true",
  "npm_config_audit_level": "low",
  "npm_config_auth_type": "legacy",
  "npm_config_before": "",
  "npm_config_bin_links": "true",
  "npm_config_browser": "",
  "npm_config_ca": "",
  "npm_config_cache": "C:\\Users\\victor brambilla\\AppData\\Roaming\\npm-cache",
  "npm_config_cache_lock_retries": "10",
  "npm_config_cache_lock_stale": "60000",
  "npm_config_cache_lock_wait": "10000",
  "npm_config_cache_max": "Infinity",
  "npm_config_cache_min": "10",
  "npm_config_cafile": "",
  "npm_config_cert": "",
  "npm_config_cidr": "",
  "npm_config_color": "true",
  "npm_config_commit_hooks": "true",
  "npm_config_depth": "Infinity",
  "npm_config_description": "true",
  "npm_config_dev": "",
  "npm_config_dry_run": "",
  "npm_config_editor": "notepad.exe",
  "npm_config_engine_strict": "",
  "npm_config_fetch_retries": "2",
  "npm_config_fetch_retry_factor": "10",
  "npm_config_fetch_retry_maxtimeout": "60000",
  "npm_config_fetch_retry_mintimeout": "10000",
  "npm_config_force": "",
  "npm_config_format_package_lock": "true",
  "npm_config_fund": "true",
  "npm_config_git": "git",
  "npm_config_git_tag_version": "true",
  "npm_config_global": "",
  "npm_config_globalconfig": "C:\\Users\\victor brambilla\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_globalignorefile": "C:\\Users\\victor brambilla\\AppData\\Roaming\\npm\\etc\\npmignore",
  "npm_config_global_style": "",
  "npm_config_group": "",
  "npm_config_ham_it_up": "",
  "npm_config_heading": "npm",
  "npm_config_https_proxy": "",
  "npm_config_if_present": "",
  "npm_config_ignore_prepublish": "",
  "npm_config_ignore_scripts": "",
  "npm_config_init_author_email": "",
  "npm_config_init_author_name": "",
  "npm_config_init_author_url": "",
  "npm_config_init_license": "ISC",
  "npm_config_init_module": "C:\\Users\\victor brambilla\\.npm-init.js",
  "npm_config_init_version": "1.0.0",
  "npm_config_json": "",
  "npm_config_key": "",
  "npm_config_legacy_bundling": "",
  "npm_config_link": "",
  "npm_config_local_address": "",
  "npm_config_loglevel": "notice",
  "npm_config_logs_max": "10",
  "npm_config_long": "",
  "npm_config_maxsockets": "50",
  "npm_config_message": "%s",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_node_options": "",
  "npm_config_node_version": "14.17.6",
  "npm_config_noproxy": "",
  "npm_config_offline": "",
  "npm_config_onload_script": "",
  "npm_config_only": "",
  "npm_config_optional": "true",
  "npm_config_otp": "",
  "npm_config_package_lock": "true",
  "npm_config_package_lock_only": "",
  "npm_config_parseable": "",
  "npm_config_prefer_offline": "",
  "npm_config_prefer_online": "",
  "npm_config_prefix": "C:\\Users\\victor brambilla\\AppData\\Roaming\\npm",
  "npm_config_preid": "",
  "npm_config_production": "",
  "npm_config_progress": "true",
  "npm_config_proxy": "",
  "npm_config_read_only": "",
  "npm_config_rebuild_bundle": "true",
  "npm_config_registry": "https://registry.npmjs.org/",
  "npm_config_rollback": "true",
  "npm_config_save": "true",
  "npm_config_save_bundle": "",
  "npm_config_save_dev": "",
  "npm_config_save_exact": "",
  "npm_config_save_optional": "",
  "npm_config_save_prefix": "^",
  "npm_config_save_prod": "",
  "npm_config_scope": "",
  "npm_config_scripts_prepend_node_path": "warn-only",
  "npm_config_script_shell": "",
  "npm_config_searchexclude": "",
  "npm_config_searchlimit": "20",
  "npm_config_searchopts": "",
  "npm_config_searchstaleness": "900",
  "npm_config_send_metrics": "",
  "npm_config_shell": "C:\\WINDOWS\\system32\\cmd.exe",
  "npm_config_shrinkwrap": "true",
  "npm_config_sign_git_commit": "",
  "npm_config_sign_git_tag": "",
  "npm_config_sso_poll_frequency": "500",
  "npm_config_sso_type": "oauth",
  "npm_config_strict_ssl": "true",
  "npm_config_tag": "latest",
  "npm_config_tag_version_prefix": "v",
  "npm_config_timing": "",
  "npm_config_tmp": "C:\\Users\\VICTOR~1\\AppData\\Local\\Temp",
  "npm_config_umask": "0000",
  "npm_config_unicode": "",
  "npm_config_unsafe_perm": "true",
  "npm_config_update_notifier": "true",
  "npm_config_usage": "",
  "npm_config_user": "",
  "npm_config_userconfig": "C:\\Users\\victor brambilla\\.npmrc",
  "npm_config_user_agent": "npm/6.14.15 node/v14.17.6 win32 x64",
  "npm_config_version": "",
  "npm_config_versions": "",
  "npm_config_viewer": "browser",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_browserslist_production_2": "not op_mini all",
  "npm_package_dependencies_axios": "^0.25.0",
  "npm_package_dependencies_history": "^5.2.0",
  "npm_package_dependencies_js_cookie": "^3.0.1",
  "npm_package_dependencies_react": "^17.0.2",
  "npm_package_dependencies_react_dom": "^17.0.2",
  "npm_package_dependencies_react_dotenv": "^0.1.3",
  "npm_package_dependencies_react_router_dom": "^6.0.0-beta.0",
  "npm_package_dependencies_react_scripts": "5.0.0",
  "npm_package_dependencies_web_vitals": "^2.1.3",
  "npm_package_dependencies__emotion_react": "^11.7.1",
  "npm_package_dependencies__emotion_styled": "^11.6.0",
  "npm_package_dependencies__mui_icons_material": "^5.2.5",
  "npm_package_dependencies__mui_lab": "^5.0.0-alpha.65",
  "npm_package_dependencies__mui_material": "^5.2.7",
  "npm_package_dependencies__mui_x_data_grid": "^5.3.0",
  "npm_package_dependencies__testing_library_jest_dom": "^5.16.1",
  "npm_package_dependencies__testing_library_react": "^12.1.2",
  "npm_package_dependencies__testing_library_user_event": "^13.5.0",
  "npm_package_description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "npm_package_devDependencies_gh_pages": "^3.2.3",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_name": "contacts",
  "npm_package_private": "true",
  "npm_package_readmeFilename": "README.md",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_package_scripts_predeploy": "npm run build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_package_scripts_test": "react-scripts test",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\victor brambilla\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OneDrive": "C:\\Users\\victor brambilla\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\Users\\victor brambilla\\Desktop\\vscode\\desafio crm7\\contacts\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;C:\\Users\\victor brambilla\\Desktop\\vscode\\desafio crm7\\contacts\\node_modules\\.bin;C:\\Program Files\\Common Files\\Siemens\\Automation\\Simatic OAM\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\AdoptOpenJDK\\jre-11.0.11.9-hotspot\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\victor brambilla\\Desktop\\gradle\\gradle-7.3.3\\bin;C:\\Users\\victor brambilla\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Users\\victor brambilla\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\victor brambilla\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\victor brambilla\\AppData\\Roaming\\npm;",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 158 Stepping 13, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "9e0d",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\Tools\\PowerShell\\Modules\\",
  "PUBLIC": "C:\\Users\\Public",
  "REACT_APP_API_URL": "https://www.zohoapis.com/crm/v2",
  "REACT_APP_GET_TOKEN": "https://accounts.zoho.com/oauth/v2/auth?client_id=1000.SK8VFQGNL3GM80PNASRZ4NNK6SVWXV&response_type=token&scope=ZohoCRM.modules.ALL&redirect_uri=http://localhost:3000/loading",
  "SESSIONNAME": "Console",
  "Simatic_OAM": "C:\\Program Files\\Common Files\\Siemens\\Automation\\Simatic OAM",
  "Simatic_OAM_DATA": "C:\\ProgramData\\Siemens\\Automation\\Simatic OAM",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\VICTOR~1\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.63.2",
  "TMP": "C:\\Users\\VICTOR~1\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-PMAO6FS",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-PMAO6FS",
  "USERNAME": "victor brambilla",
  "USERPROFILE": "C:\\Users\\victor brambilla",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\victor brambilla\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\victor brambilla\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-b0306f2064-sock",
  "windir": "C:\\WINDOWS",
  "_prog": "node"
};